spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/test_task
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      format_sql: true
logging:
  level:
    root: INFO
springdoc:
  api-docs:
    path: /api-docs
